import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { profile } from "../habits.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
registerMainMenuItem({ label: "⚙️ Manage habits", data: "habits:manage", order: 40 });
const composer = new Composer<Ctx>();
function keyboard(ctx: Ctx) { const p = profile(ctx.session); return inlineKeyboard([...(p?.habits ?? []).map((h) => [inlineButton(`${h.active ? "Pause" : "Resume"} ${h.name}`, `habit:toggle:${h.id}`), inlineButton("Delete", `habit:delete:${h.id}`)]), [inlineButton("Adjust time zone", "habit:timezone")], [inlineButton("Milestones", "settings:milestones")], [inlineButton("Back to menu", "menu:main")]]); }
async function show(ctx: Ctx, edit = false) { const p = profile(ctx.session); const text = !p?.habits.length ? "No habits yet — tap ➕ Create habit to add one." : "Choose a habit to pause, resume, or delete."; if (edit) await ctx.editMessageText(text, { reply_markup: keyboard(ctx) }); else await ctx.reply(text, { reply_markup: keyboard(ctx) }); }
composer.callbackQuery("habits:manage", async (ctx) => { await ctx.answerCallbackQuery(); await show(ctx, true); });
composer.callbackQuery(/^habit:toggle:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const h = profile(ctx.session)?.habits.find((x) => x.id === ctx.match[1]); if (!h) { await ctx.reply("That habit is no longer here."); return; } h.active = !h.active; await ctx.reply(h.active ? `“${h.name}” is active again.` : `“${h.name}” is paused. Take the space you need.`, { reply_markup: keyboard(ctx) }); });
composer.callbackQuery(/^habit:delete:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const p = profile(ctx.session); const h = p?.habits.find((x) => x.id === ctx.match[1]); if (!p || !h) { await ctx.reply("That habit is no longer here."); return; } await ctx.reply(`Delete “${h.name}”? This removes its private history.`, { reply_markup: inlineKeyboard([[inlineButton("Delete", `habit:confirm-delete:${h.id}`), inlineButton("Keep habit", "habits:manage")]]) }); });
composer.callbackQuery(/^habit:confirm-delete:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const p = profile(ctx.session); if (!p) return; const h = p.habits.find((x) => x.id === ctx.match[1]); p.habits = p.habits.filter((x) => x.id !== ctx.match[1]); p.checkins = p.checkins.filter((x) => x.habitId !== ctx.match[1]); await ctx.reply(h ? `“${h.name}” and its history have been removed.` : "That habit was already removed.", { reply_markup: keyboard(ctx) }); });
composer.callbackQuery("settings:milestones", async (ctx) => { await ctx.answerCallbackQuery(); const p = profile(ctx.session); if (!p) { await ctx.reply("Create a habit first, then you can choose milestone reminders."); return; } p.milestones = !p.milestones; await ctx.reply(p.milestones ? "Milestone celebrations are on." : "Milestone celebrations are off.", { reply_markup: keyboard(ctx) }); });
export default composer;
